version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knowledgebase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/knowledgebase
    GEMINI_API_KEY: AIzaSyB0cXNiUsaPtFvyPYrMPWQfecCoIqsK8yA
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data:
